CREATE TABLE animals
(
    animal_id   NUMBER(4) CONSTRAINT animals_pk PRIMARY KEY 
    ,name       VARCHAR2(30 CHAR) NOT NULL
    ,color      VARCHAR2(20 CHAR)
    ,leg_count  NUMBER(5) NOT NULL  
);

-- Create a sequence to generate the next value for animal_id
CREATE SEQUENCE animals_seq
  START WITH 1  -- The first value generated by the sequence
  INCREMENT BY 1  -- Increment the value by 1 each time
  NOCACHE  -- Do not cache sequence values in memory
  NOCYCLE  -- Do not allow the sequence to cycle back to the start value
;

-- Create a trigger that automatically populates animal_id with the next value from the sequence
CREATE OR REPLACE TRIGGER animals_trg
  BEFORE INSERT ON animals
  FOR EACH ROW
BEGIN
  SELECT animals_seq.NEXTVAL INTO :new.animal_id FROM dual;
END;
/

-- ID's from inserts are ignored.
INSERT INTO animals VALUES (1, 'Capybara', 'brown', 4);
INSERT INTO animals VALUES (2, 'Snake', 'Green', 0);
INSERT INTO animals VALUES (3, 'Skunk', 'black', 4);
INSERT INTO animals VALUES (4, 'Bnuuy', 'GREY', 4);
INSERT INTO animals VALUES (5, 'Human', 'Pink', 2);
INSERT INTO animals VALUES (6, 'Bat', 'black', 3);
INSERT INTO animals VALUES (7, 'Snek', 'brownish', 1);
INSERT INTO animals (animal_id, name, color, leg_count) VALUES (200, 'BIRD', 'green', 13);
commit;

INSERT INTO animals (name, color, leg_count)
VALUES ('Fluffy', 'White', 4);


DROP table animals;